### ISSUE TITLE
No verification email for new account

### ISSUE THREAD

**Issue by bdubbbs** [Film-Aficionado/filmaf.com#14]
Created a new account but never received the verification email to complete set up.

**Comment by drdouglasghd** [comment]
Can you share your email address? I can verify the account setup in the database.

**Comment by bdubbbs** [comment]
Hi,

I was able to create the new account a couple of weeks ago, so we're all good.


Thank you,

Brian

**Comment by drdouglasghd** [comment]
Excellent. Thanks.
