### ISSUE TITLE
Never received password reset email

### ISSUE THREAD

**Issue by Hahe71** [Film-Aficionado/filmaf.com#15]
Couldn't log in and then tried resetting my password. Never got the email and still can't log in.

**Comment by drdouglasghd** [comment]
Can you please share your email address? I will confirm in the database.

**Comment by Hahe71** [comment]
Hahecopyright99@aol.com

**Comment by drdouglasghd** [comment]
Sent you an email from my gmail account. Let me know if you got it.

**Comment by Hahe71** [comment]
Got it. Back in my account. Thank you!

**Comment by drdouglasghd** [comment]
Sweet!
