### ISSUE TITLE
Old Login

### ISSUE THREAD

**Issue by Ashraimi** [Film-Aficionado/filmaf.com#18]
Cannot access acct cause the email I signed up under has been closed for years and I never updated to my current one, so I'm unable to get password resets.

**Comment by drdouglasghd** [comment]
Can you share your old and new email address? We can try to update it?

**Comment by Ashraimi** [comment]
Hi Geoff!

My old address was ashraimi@bellsouth.net and my new one is
ashraimi1@gmail.com.

Thank you so much for your help!
Brian

**Comment by drdouglasghd** [comment]
I have processed an email address change for your account. Please let me know if you received a verification email to your gmail address.

**Comment by Ashraimi** [comment]
I did! Thank you!

**Comment by drdouglasghd** [comment]
Excellent.
