### ISSUE TITLE
No Password Reset Email

### ISSUE THREAD

**Issue by Spottedfeather** [Film-Aficionado/filmaf.com#21]
C'mon guys. It's been months and nobody can log in. We put in our info for an email to reset our passwords...but nobody gets the email. I just saw on facebook that says you fixed it....but you didn't say HOW you fixed it. Get on the ball, please.

**Comment by drdouglasghd** [comment]
I just reset my password today and received an email, and was able to login. 

Please let us know what you have tried, and we can try to help.

**Comment by Spottedfeather** [comment]
I have just tried to get an email to reset my password because that's the only thing you can do.     On Monday, June 8, 2020, 08:06:32 PM CDT, Geoff Douglas <notifications@github.com> wrote:  
 
 


I just reset my password today and received an email, and was able to login.

Please let us know what you have tried, and we can try to help.

**Comment by drdouglasghd** [comment]
Can you confirm your email address here? I can verify that is what's on the account.

**Comment by Spottedfeather** [comment]
> Can you confirm your email address here? I can verify that is what's on the account.

tir_na_faer@yahoo.com

**Comment by drdouglasghd** [comment]
I just emailed you from gmail. Let me know if you get that one.
