### ISSUE TITLE
broken IMDb links

### ISSUE THREAD

**Issue by brente78** [Film-Aficionado/filmaf.com#22]
Clicking on the IMDb links for any given listing currently takes you to a page on IMDb that says "Why am I being redirected to IMDb?" instead of taking you to the page for the film.

**Comment by drdouglasghd** [comment]
Did this just start, or has it been like this for a while?

**Comment by brente78** [comment]
I think it was a problem earlier this year for a while, then it got fixed around the time you were first fixing everything else, and then I just noticed it wasn't working right again earlier this week.

**Comment by drdouglasghd** [comment]
I am seeing a Security Warning, because the SSL certificate doesn't match the domain.

**Comment by drdouglasghd** [comment]
@brente78 Let me know if the imdb links are working now.

**Comment by brente78** [comment]
It does appear to be working now, thanks!
