### ISSUE TITLE
Movies Not In Film Aficionado Database

### ISSUE THREAD

**Issue by AlphaOmegaSid** [Film-Aficionado/filmaf.com#24]
Is there a Film Aficionado member/contributor that I can contact to input movies not found in database with time and expertise? If so, how can I contact them?

Thanks in advance.

**Comment by drdouglasghd** [comment]
@brente78 Would know how that works.

As a user, I believe you submit a new DVD then other users can accept it?

**Comment by brente78** [comment]
Yes, I do it a lot. Under "My Contribution" you go to "Submit New DVD." There's a form there you can fill out with as much information as possible. There are info boxes for each field that explain the process, and then if there are areas in which the submission is lacking, a moderator will eventually review the submission and provide pointers.

If any specific questions come up, I'm happy to answer. But also, for any given listing in the database you can click on "Correct listing info" and it will pull up the completed form. You won't want to actually correct anything on the form, but seeing how it is filled out can give you an idea of what is expected for your new listings.

**Comment by AlphaOmegaSid** [comment]
Hey, Brente. Yeah, I used to input movie data myself for the site, but do not have the time anymore. I was able to get a hold of Captveg. He was happy to contribute on Asian and European films not known on Film Aficionado, will be emailing him on these kinds of films.

Infinite thanks to the friendly/helpful Film Aficionado staff and users.
