### ISSUE TITLE
Still cannot login to my 2002 account.

### ISSUE THREAD

**Issue by AlphaOmegaSid** [Film-Aficionado/filmaf.com#9]

**Comment by drdouglasghd** [comment]
If you can share your email address, I can try to get you the reset password information.

**Comment by AlphaOmegaSid** [comment]
Greetings, Geoff. That is my main email address that you have sent the below message to. Please, send me a reset password.
User: AlphaOmegaSidEmail: granturismoelite@aol.com


-----Original Message-----
